import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'
import { Navbar } from '../../components/Navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home - fernando</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
    
      <main className={styles.main}>
      <h1>Contact Page</h1>
        <h1 className={styles.title}>
          {/* Ir a <a href="/about">About</a> */}
          Ir a <Link href="/">Home</Link>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

      </main> 

    </div>
  )
}