import React from 'react'
import { Navbar } from '../NavBar'
import styles from './MainLayout.module.css'

export const MainLayout = ({children}) => {
    return (
        <div className={styles.container}>
          <Head>
            <title>About - Fernando</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Navbar />
          <main className={styles.main}>
            
            { children }
    
          </main>
    
        </div>
      )
}
